package com.hopon.dao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import com.hopon.utils.QueryExecuter;
import com.hopon.dto.CityDTO;
import com.mysql.jdbc.Statement;

public class CityDAO {

	public CityDTO findCityByName(Connection con, String cityName, String stateName) throws SQLException {
		StringBuilder query = new StringBuilder();
		query.append("select tbl_citylist.city_id, tbl_citylist.city_name, tbl_citylist.latitude, tbl_citylist.longitude, tbl_citylist.state from tbl_citylist where tbl_citylist.city_name = ?");
		if(stateName != null && stateName.length() > 0) {
			query.append(" AND tbl_citylist.state = ?");
		}
		CityDTO dto = new CityDTO();
		
		PreparedStatement pstmt = con.prepareStatement(query.toString());
		pstmt.setString(1, cityName);
		if(stateName != null && stateName.length() > 0) {
			pstmt.setString(2, stateName);
		}
		ResultSet rs = QueryExecuter.getResultSet(pstmt, query.toString());
		if(rs.next()) {
			dto.setCityId(rs.getInt(1));
			dto.setCityName(rs.getString(2));
			dto.setLatitude(rs.getString(3));
			dto.setLongitude(rs.getString(4));
			dto.setState(rs.getString(5));
		}
		rs.close();
		pstmt.close();
		if(dto.getCityId() <= 0) {
			query = new StringBuilder();
			query.append("INSERT INTO tbl_citylist (city_id, city_name, latitude, longitude, state) VALUES(null, ?, ?, ?, ?)");
			pstmt = con.prepareStatement(query.toString() ,Statement.RETURN_GENERATED_KEYS);
			pstmt.setString(1, cityName);
			pstmt.setFloat(2, 0);
			pstmt.setFloat(3, 0);
			pstmt.setString(4, stateName);
			pstmt.executeUpdate();
			ResultSet tableKeys = pstmt.getGeneratedKeys();
			tableKeys.next();
			int autoGeneratedID = tableKeys.getInt(1);
			tableKeys.close();
			pstmt.close();
			dto.setCityId(autoGeneratedID);
			dto.setCityName(cityName);
			dto.setState(stateName);
		}
		return dto;
	}
	public List<CityDTO> findCity(Connection con, String finalValue) throws SQLException {
		StringBuilder query = new StringBuilder();
		query.append("select tbl_citylist.city_id, tbl_citylist.city_name, tbl_citylist.latitude, tbl_citylist.longitude, tbl_citylist.state from tbl_citylist ");
		if(!(finalValue == null || finalValue.equals(""))){
			query.append(" where tbl_citylist.city_name like '%"  + finalValue + "%'");
		}
		List<CityDTO> cityList = new ArrayList<CityDTO>();
		PreparedStatement pstmt = con.prepareStatement(query.toString());
		ResultSet rs = QueryExecuter.getResultSet(pstmt, query.toString());
		while(rs.next()) {
			CityDTO dto = new CityDTO();
			dto.setCityId(rs.getInt(1));
			dto.setCityName(rs.getString(2));
			dto.setLatitude(rs.getString(3));
			dto.setLongitude(rs.getString(4));
			dto.setState(rs.getString(5));

			cityList.add(dto);
		}
		rs.close();
		pstmt.close();
		return cityList;
	}
}
